server:
  port: 8181

spring:
  datasource:
    username: root
    password: QWEasd123
    url: jdbc:mysql://localhost:3306/students?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.run.students.dao
  configuration:
    map-underscore-to-camel-case: true # 驼峰转换